In [1]:
import pandas as pd
import numpy as np

In [2]:
train=pd.read_csv('train.csv')

In [3]:
print(train.head())

   Id  Hazard  T1_V1  T1_V2  T1_V3 T1_V4 T1_V5 T1_V6 T1_V7 T1_V8   ...    \
0   1       1     15      3      2     N     B     N     B     B   ...     
1   2       4     16     14      5     H     B     N     B     B   ...     
2   3       1     10     10      5     N     K     N     B     B   ...     
3   4       1     18     18      5     N     K     N     B     B   ...     
4   5       1     13     19      5     N     H     N     B     B   ...     

  T2_V6  T2_V7 T2_V8 T2_V9  T2_V10  T2_V11 T2_V12 T2_V13 T2_V14  T2_V15  
0     2     37     1    11       6       Y      N      E      2       2  
1     2     22     1    18       5       Y      Y      E      2       1  
2     6     37     2    14       6       Y      Y      E      6       1  
3     2     25     1     1       6       Y      N      C      2       6  
4     1     22     1     2       7       N      N      E      1       1  

[5 rows x 34 columns]


In [4]:
print(train['T1_V1'].unique())

[15 16 10 18 13 14  8  5  4  3 11  9  7 12  6 19  1  2 17]


In [5]:
train.columns

Index(['Id', 'Hazard', 'T1_V1', 'T1_V2', 'T1_V3', 'T1_V4', 'T1_V5', 'T1_V6',
       'T1_V7', 'T1_V8', 'T1_V9', 'T1_V10', 'T1_V11', 'T1_V12', 'T1_V13',
       'T1_V14', 'T1_V15', 'T1_V16', 'T1_V17', 'T2_V1', 'T2_V2', 'T2_V3',
       'T2_V4', 'T2_V5', 'T2_V6', 'T2_V7', 'T2_V8', 'T2_V9', 'T2_V10',
       'T2_V11', 'T2_V12', 'T2_V13', 'T2_V14', 'T2_V15'],
      dtype='object')

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50999 entries, 0 to 50998
Data columns (total 34 columns):
Id        50999 non-null int64
Hazard    50999 non-null int64
T1_V1     50999 non-null int64
T1_V2     50999 non-null int64
T1_V3     50999 non-null int64
T1_V4     50999 non-null object
T1_V5     50999 non-null object
T1_V6     50999 non-null object
T1_V7     50999 non-null object
T1_V8     50999 non-null object
T1_V9     50999 non-null object
T1_V10    50999 non-null int64
T1_V11    50999 non-null object
T1_V12    50999 non-null object
T1_V13    50999 non-null int64
T1_V14    50999 non-null int64
T1_V15    50999 non-null object
T1_V16    50999 non-null object
T1_V17    50999 non-null object
T2_V1     50999 non-null int64
T2_V2     50999 non-null int64
T2_V3     50999 non-null object
T2_V4     50999 non-null int64
T2_V5     50999 non-null object
T2_V6     50999 non-null int64
T2_V7     50999 non-null int64
T2_V8     50999 non-null int64
T2_V9     50999 non-null int64
T2_V10    

In [7]:
for col in train.columns:
    if train[col].dtype == object:
        print(col,train[col].unique())

T1_V4 ['N' 'H' 'E' 'W' 'B' 'C' 'S' 'G']
T1_V5 ['B' 'K' 'H' 'C' 'I' 'A' 'D' 'J' 'E' 'L']
T1_V6 ['N' 'Y']
T1_V7 ['B' 'D' 'A' 'C']
T1_V8 ['B' 'D' 'A' 'C']
T1_V9 ['D' 'C' 'E' 'F' 'B' 'G']
T1_V11 ['B' 'H' 'I' 'M' 'L' 'J' 'E' 'A' 'F' 'N' 'D' 'K']
T1_V12 ['B' 'C' 'D' 'A']
T1_V15 ['A' 'D' 'C' 'H' 'N' 'S' 'W' 'F']
T1_V16 ['B' 'R' 'J' 'K' 'D' 'C' 'N' 'E' 'I' 'F' 'M' 'H' 'A' 'Q' 'G' 'L' 'P' 'O']
T1_V17 ['N' 'Y']
T2_V3 ['N' 'Y']
T2_V5 ['B' 'C' 'A' 'D' 'E' 'F']
T2_V11 ['Y' 'N']
T2_V12 ['N' 'Y']
T2_V13 ['E' 'C' 'A' 'D' 'B']


In [31]:
for col in train.columns:
    if train[col].dtype == np.int64 and (not(col=='Id' or col=='Hazard')):
        print(col,train[col].unique())

T1_V1 [15 16 10 18 13 14  8  5  4  3 11  9  7 12  6 19  1  2 17]
T1_V2 [ 3 14 10 18 19 12 17 20  2  4  7 15 23  6 13  5 21 11  1  8  9 16 22 24]
T1_V3 [2 5 1 4 3 6 9 7 8]
T1_V10 [ 7 12  3  8  2]
T1_V13 [15 10 20  5]
T1_V14 [1 3 2 4 0]
T2_V1 [ 36  78  71  75  65 100  83  20  88  86  23  49  92  41  33  81  72  77
  61  38  18  32  98  60  52  45  57   7  67  39  59  85  62  54  66  44
  97  46  76  55  35  40  50  93  43  19  82  34  64  30  80  63  47  13
  48   8  89  11  31  24  84  99  79  91  26  73   1  29  25  69  21  90
  53  74  42  58  14  87  12  27  37  28  94  15  51  17  96  70  22  95
  56   9  68  16   4   5   6  10   2   3]
T2_V2 [11 10 21 13 14 12  7 15  8  6 16 18  9 17 19 24 25  5 28 29 20 30 22 26 23
 31  3 27 32  2 34  4 33 39  1 37 35 36 38]
T2_V4 [10 17 13 15 11 14 16  5  4 12  3 19  9 18  7  6  2  8 22 20 21  1]
T2_V6 [2 6 1 4 3 5 7]
T2_V7 [37 22 25 40 34 31 28]
T2_V8 [1 2 3]
T2_V9 [11 18 14  1  2  5 20 13  6  7  3  4 19 16 21 12  9 10 17 25 24  8 23 15 22]
T2_V

In [9]:
len(train.Id.unique())

50999

In [10]:
test=pd.read_csv('test.csv')

In [11]:
test.head()

Id  T1_V1  T1_V2  T1_V3 T1_V4 T1_V5 T1_V6 T1_V7 T1_V8 T1_V9   ...    T2_V6  \
0   6      2     13      4     C     A     Y     B     B     D   ...        2   
1   7     10     10      7     N     C     Y     B     B     D   ...        3   
2   8      9     20      4     N     H     Y     B     B     E   ...        2   
3   9     11     18      2     N     H     Y     B     B     D   ...        4   
4  10      4      5      4     H     K     Y     B     B     E   ...        2   

  T2_V7 T2_V8  T2_V9  T2_V10 T2_V11 T2_V12 T2_V13  T2_V14  T2_V15  
0    28     1     22       6      Y      N      E       2       7  
1    28     1      4       3      Y      N      E       5       8  
2    22     1      1       7      N      N      C       6       1  
3    40     1     20       6      Y      N      E       5       5  
4    34     1     11       7      Y      Y      E       2       1  

[5 rows x 33 columns]

In [12]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51000 entries, 0 to 50999
Data columns (total 33 columns):
Id        51000 non-null int64
T1_V1     51000 non-null int64
T1_V2     51000 non-null int64
T1_V3     51000 non-null int64
T1_V4     51000 non-null object
T1_V5     51000 non-null object
T1_V6     51000 non-null object
T1_V7     51000 non-null object
T1_V8     51000 non-null object
T1_V9     51000 non-null object
T1_V10    51000 non-null int64
T1_V11    51000 non-null object
T1_V12    51000 non-null object
T1_V13    51000 non-null int64
T1_V14    51000 non-null int64
T1_V15    51000 non-null object
T1_V16    51000 non-null object
T1_V17    51000 non-null object
T2_V1     51000 non-null int64
T2_V2     51000 non-null int64
T2_V3     51000 non-null object
T2_V4     51000 non-null int64
T2_V5     51000 non-null object
T2_V6     51000 non-null int64
T2_V7     51000 non-null int64
T2_V8     51000 non-null int64
T2_V9     51000 non-null int64
T2_V10    51000 non-null int64
T2_V11    

In [13]:
sample=pd.read_csv('sample_submission.csv')

In [14]:
sample.head()

Id  Hazard
0   6       0
1   7       0
2   8       0
3   9       0
4  10       0

In [15]:
test['Id'].count()

51000

In [16]:
test['Id'].unique()

array([     6,      7,      8, ..., 101995, 101996, 101997], dtype=int64)

In [17]:
train['Hazard'].unique()

array([ 1,  4,  5,  7, 15, 14,  8, 16,  6, 11,  3, 13,  2, 18, 10, 17, 22,
        9, 21, 20, 12, 19, 37, 23, 28, 27, 31, 38, 41, 26, 33, 29, 30, 25,
       24, 36, 51, 42, 34, 46, 32, 69, 40, 35, 44, 39, 49, 52, 63, 64], dtype=int64)

In [18]:
train['Hazard'].count()

50999

In [19]:
train.tail()

Id  Hazard  T1_V1  T1_V2  T1_V3 T1_V4 T1_V5 T1_V6 T1_V7 T1_V8  \
50994  101992       7     12     24      1     N     H     Y     B     B   
50995  101993       4     12     17      4     N     K     N     B     B   
50996  101994       3     18      7      5     W     B     Y     B     B   
50997  101998      14     18     17      5     B     A     N     B     D   
50998  101999       9      5     15      3     B     I     Y     B     B   

        ...   T2_V6  T2_V7 T2_V8 T2_V9  T2_V10  T2_V11 T2_V12 T2_V13 T2_V14  \
50994   ...       4     25     2     9       7       Y      Y      E      4   
50995   ...       2     37     1     4       7       N      N      A      5   
50996   ...       2     28     1     1       2       N      N      E      1   
50997   ...       1     40     1     7       4       Y      N      C      2   
50998   ...       2     40     1    16       1       Y      N      E      5   

       T2_V15  
50994       1  
50995       2  
50996       1  
50997       6  
50998       4  

[5 rows x 34 columns]

In [20]:
train.index=train['Id']

In [21]:
train.head()

Id  Hazard  T1_V1  T1_V2  T1_V3 T1_V4 T1_V5 T1_V6 T1_V7 T1_V8   ...    \
Id                                                                  ...     
1    1       1     15      3      2     N     B     N     B     B   ...     
2    2       4     16     14      5     H     B     N     B     B   ...     
3    3       1     10     10      5     N     K     N     B     B   ...     
4    4       1     18     18      5     N     K     N     B     B   ...     
5    5       1     13     19      5     N     H     N     B     B   ...     

   T2_V6  T2_V7 T2_V8 T2_V9  T2_V10  T2_V11 T2_V12 T2_V13 T2_V14  T2_V15  
Id                                                                        
1      2     37     1    11       6       Y      N      E      2       2  
2      2     22     1    18       5       Y      Y      E      2       1  
3      6     37     2    14       6       Y      Y      E      6       1  
4      2     25     1     1       6       Y      N      C      2       6  
5      1     22     1     2       7       N      N      E      1       1  

[5 rows x 34 columns]

In [22]:
train.index

Int64Index([     1,      2,      3,      4,      5,     12,     15,     19,
                21,     22,
            ...
            101984, 101986, 101987, 101988, 101991, 101992, 101993, 101994,
            101998, 101999],
           dtype='int64', name='Id', length=50999)

In [23]:
Y=train[['Id','Hazard']]

In [24]:
Y.head()

Id  Hazard
Id            
1    1       1
2    2       4
3    3       1
4    4       1
5    5       1

In [25]:
X=train.loc[:,'T1_V1':]

In [26]:
X.head()

T1_V1  T1_V2  T1_V3 T1_V4 T1_V5 T1_V6 T1_V7 T1_V8 T1_V9  T1_V10  ...    \
Id                                                                   ...     
1      15      3      2     N     B     N     B     B     D       7  ...     
2      16     14      5     H     B     N     B     B     C      12  ...     
3      10     10      5     N     K     N     B     B     E      12  ...     
4      18     18      5     N     K     N     B     B     E       3  ...     
5      13     19      5     N     H     N     B     B     E       7  ...     

   T2_V6 T2_V7  T2_V8  T2_V9 T2_V10 T2_V11 T2_V12  T2_V13  T2_V14 T2_V15  
Id                                                                        
1      2    37      1     11      6      Y      N       E       2      2  
2      2    22      1     18      5      Y      Y       E       2      1  
3      6    37      2     14      6      Y      Y       E       6      1  
4      2    25      1      1      6      Y      N       C       2      6  
5      1    22      1      2      7      N      N       E       1      1  

[5 rows x 32 columns]

In [27]:
X.shape

(50999, 32)

In [28]:
Y.shape

(50999, 2)

In [29]:
del Y['Id']

In [30]:
Y.head()

Hazard
Id        
1        1
2        4
3        1
4        1
5        1